package com.earnit.app.ui

data class Quote(
    val text: String,
    val source: String = "",
)

internal val motivationalQuotes =
    listOf(
        // Original EarnIt quotes
        Quote("Every point is proof you showed up."),
        Quote("Small wins stack into big rewards."),
        Quote("Progress, not perfection."),
        Quote("Today's effort is tomorrow's reward."),
        Quote("Consistency beats motivation every time."),
        Quote("Another day, another chance to level up."),
        Quote("Do it for future you."),
        Quote("Momentum starts with one small step."),
        Quote("Your future self is rooting for you."),
        Quote("Discipline is self-love in disguise."),
        Quote("The only bad workout is the one you skipped."),
        // Proverbs & anonymous sayings
        Quote("Even if you fall on your face, you're still moving forward."),
        Quote("When you reach the end of your rope, tie a knot in it and hang on."),
        Quote("He who moves a mountain begins by carrying away small stones."),
        Quote("Even a snail will eventually reach the Ark."),
        Quote("Fall down seven times, stand up eight.", "Japanese proverb"),
        Quote("Rome wasn't built in a day."),
        Quote("The best time to plant a tree was twenty years ago. The second best time is now."),
        // Historical figures & authors
        Quote(
            "Don't worry about the world coming to an end today. It's already tomorrow in Australia.",
            "Charles Schulz",
        ),
        Quote("Life is a shipwreck, but we must not forget to sing in the lifeboats.", "Voltaire"),
        Quote("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
        Quote("Never give up on something that you can't go a day without thinking about.", "Winston Churchill"),
        Quote("As much as talent counts, effort counts twice.", "Angela Duckworth"),
        Quote("I dare to be honest, and I fear no labour.", "Robert Burns"),
        Quote("Life is like riding a bicycle. To keep your balance, you must keep moving.", "Albert Einstein"),
        Quote("Be the change you wish to see in the world.", "Mahatma Gandhi"),
        Quote("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
        Quote("Change your life today. Don't gamble on the future, act now, without delay.", "Simone de Beauvoir"),
        Quote(
            "I may not have gone where I intended to go, but I think I have ended up where I needed to be.",
            "Douglas Adams",
        ),
        Quote("Forever is composed of nows.", "Emily Dickinson"),
        Quote("Today's accomplishments were yesterday's impossibilities.", "Robert H. Schuller"),
        Quote(
            "Someone is sitting in the shade today because someone planted a tree a long time ago.",
            "Warren Buffett",
        ),
        Quote(
            "Success is not final, failure is not fatal: it is the courage to continue that counts.",
            "Winston Churchill",
        ),
        Quote("The most difficult thing is the decision to act; the rest is merely tenacity.", "Amelia Earhart"),
        Quote("You must do the things you think you cannot do.", "Eleanor Roosevelt"),
        Quote("It is never too late to be what you might have been.", "George Eliot"),
        Quote("Slow and steady wins the race.", "Aesop"),
        Quote("A journey of a thousand miles begins with a single step.", "Lao Tzu"),
        Quote("If you add a little to a little, and do this often, soon the little will become great.", "Hesiod"),
        Quote("Dripping water hollows out stone, not through force but through persistence.", "Ovid"),
        Quote("No great thing is created suddenly, any more than a bunch of grapes or a fig.", "Epictetus"),
        Quote(
            "It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.",
            "Seneca",
        ),
        Quote("The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius"),
        Quote("Little strokes fell great oaks.", "Benjamin Franklin"),
        Quote("Well done is better than well said.", "Benjamin Franklin"),
        Quote("Our greatest glory consists not in never falling, but in rising every time we fall.", "Oliver Goldsmith"),
        Quote("Great things are done by a series of small things brought together.", "Vincent van Gogh"),
        Quote("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
        Quote("Optimism is the faith that leads to achievement.", "Helen Keller"),
        Quote("To strive, to seek, to find, and not to yield.", "Alfred, Lord Tennyson"),
        Quote("Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", "Samuel Beckett"),
        Quote("I am not afraid of storms, for I am learning how to sail my ship.", "Louisa May Alcott"),
        Quote("You may encounter many defeats, but you must not be defeated.", "Maya Angelou"),
        Quote("Nothing will work unless you do.", "Maya Angelou"),
        Quote("Life is not easy for any of us. But what of that? We must have perseverance.", "Marie Curie"),
        Quote("Feet, what do I need you for when I have wings to fly?", "Frida Kahlo"),
        Quote("One child, one teacher, one book, one pen can change the world.", "Malala Yousafzai"),
        Quote("Technique and ability alone do not get you to the top; it is the willpower that is most important.", "Junko Tabei"),
        Quote("Never be limited by other people's limited imaginations.", "Mae Jemison"),
        Quote("I have learned over the years that when one's mind is made up, this diminishes fear.", "Rosa Parks"),
        // TV & film characters
        Quote("Just keep swimming.", "Dory, Finding Nemo"),
        Quote("Why do we fall? So we can learn to pick ourselves up.", "Alfred, Batman Begins"),
        Quote("Whenever you're ready.", "Coach Beard, Ted Lasso"),
        Quote("Hakuna matata — it means no worries.", "Timon & Pumbaa, The Lion King"),
        Quote("The very things that hold you down are going to lift you up.", "Timothy Mouse, Dumbo"),
        Quote("Things are only impossible until they're not.", "Captain Picard, Star Trek: TNG"),
        Quote("It is possible to commit no mistakes and still lose. That is not a weakness. That is life.", "Captain Picard, Star Trek: TNG"),
        Quote("Live long and prosper.", "Spock, Star Trek"),
        Quote("Change is the essential process of all existence.", "Spock, Star Trek"),
        Quote("I can do this all day.", "Steve Rogers, Captain America"),
        Quote("Just because something works doesn't mean it can't be improved.", "Shuri, Black Panther"),
        Quote("May the Force be with you.", "Star Wars"),
        Quote("To infinity and beyond!", "Buzz Lightyear, Toy Story"),
        Quote("The cake is a lie.", "Portal"),
        // Modern parody quotes
        Quote("Keep calm and procrastinate faster."),
        Quote("Keep calm and fail forward."),
        Quote("Modern problems require modern discipline."),
        Quote("Ask not what your streak can do for you."),
        Quote("Where there's a will, there's a checkbox."),
    )
